### PR TITLE
Add Setter, Getter, conversions, compositions

### PR DESCRIPTION
**Pull request by LiamGoodacre**
I still have yet to add tests but, so far:

* Added Setter
* Added Getter
* Added all possible conversions (e.g `asGetter`, `asFold`, etc)
* Added all possible compositions
* Fixed some typos (Options/Option -> Optional)
* Minor rearrangement so conversions and compositions are grouped

Hopefully I haven't missed any.

### CODE REVIEW

**Comment by LiamGoodacre** [comment]
For some reason `npm run prettier` fails, but it doesn't tell me why.

**Comment by gcanti** [comment]
Please, add the following script to package.json

```
"fix-prettier": "prettier --no-semi --single-quote --print-width 120 --parser typescript --write \"{src,test,exercises}/**/*.ts\""
```

should fix all style complaints

**Comment by gcanti** [comment]
Nice. Let me know when you're ok with this, I'll prepare a new release

**Comment by LiamGoodacre** [comment]
My plan tonight is to add `set` to `Setter`, and then write some tests.

I am wondering what your thoughts are on having an optic sub-typing hierarchy?
E.g `class Getter<S, A> extends Fold<S, A>`.
Or, some way of writing functions that, say, require a Fold, but you can give a Getter, because there is a trivial conversion.

**Comment by gcanti** [comment]
> I am wondering what your thoughts are on having an optic sub-typing hierarchy?

Personally I try to write TypeScript without resorting to sub-typing. In other words I try to write TypeScript as if it were PureScript (see for example how `Option` is implemented in fp-ts using a union instead of a hierarchy like in Scala). I mean, I'm not hostile to the usage of sub-typing if it's exclusively an implementation detail, however I'd be worried if the APIs works *because* of that. Does it make sense?

**Comment by LiamGoodacre** [comment]
Yes, that makes perfect sense.

**Comment by gcanti** [comment]
btw maybe I should add a `_tag` field to all classes in order to fake nominal types as I do in fp-ts, so one can build tagged unions with them, for example

```ts
function myapi<S, A>(optic: Getter<S, A> | Fold<S, A>): A {
  switch (optic._tag)  {
    case 'Getter' :
      ...
    case 'Fold' :
      ...
  }
}
```

**Comment by LiamGoodacre** [comment]
Yeah that sounds useful.

I think I've done everything I wanted to in this pull request.
Let me know if you want me to change anything.

**Comment by gcanti** [comment]
Released in https://github.com/gcanti/monocle-ts/releases/tag/0.3.1

**Pull request merged**
