### PR TITLE
upgrade to latest fp-ts (0.5)

### PR DESCRIPTION
**Pull request by gcanti**
This is a test of upgrading to latest fp-ts (not yet officially released) + curry all the things

/cc @raveclassic for review

### CODE REVIEW

**Comment by raveclassic** [comment]
@gcanti What's the status? Is it ready for `monocle-ts@next`?

**Comment by gcanti** [comment]
@raveclassic I guess so

**Comment by gcanti** [comment]
Published as `monocle-ts@next`

**Comment by raveclassic** [comment]
Thanks!

**Pull request merged**
